### ISSUE TITLE
Moving Mobile Indicator

### ISSUE THREAD

**Issue by DracoClaw** [DiscordStyles/RadialStatus#1]
So IDK what happened to my last issue, so I've made this one. I was thinking about the mobile indicator, and where would be a good place to put it, what about `nameAndDecorators-5FJ2dg` where the Nitro icon is?

**Comment by Gibbu** [comment]
Not possible. I only have access to picture and cannot place it dynamically after names.
I can definitely move but then then it would reduce the amount of compatibility of themes.

**Comment by DracoClaw** [comment]
Hey so I was thinking, maybe remove the icon completely. Or have a new color option to represent mobile.

**Comment by Gibbu** [comment]
Changing the colour would be possible. But removing the icon is a no go.

**Comment by DracoClaw** [comment]
Alright. Well I think a color would be good.
