### ISSUE TITLE
When someone changes their status, the circle sometimes disappears

### ISSUE THREAD

**Issue by bettercalldelta** [DiscordStyles/RadialStatus#10]
Before:
![Выделение_359](https://user-images.githubusercontent.com/76256620/118389488-d8fcd380-b632-11eb-9bff-ce580bed4442.png)
After:
![Выделение_360](https://user-images.githubusercontent.com/76256620/118389486-d7cba680-b632-11eb-97a1-951de2094691.png)

btw I want to say hello to my mother

**Comment by Gibbu** [comment]
Fixed.
