### ISSUE TITLE
new user popout color gap does not change shape

### ISSUE THREAD

**Issue by Tracenji** [DiscordStyles/RadialStatus#11]
new discord update added this
i understand that this is a new update so you have not had time to fix it but i just wanted to let you know just in case you hadn't noticed yet
changing avatar shape does not change the shape of the no color border here, 
![image](https://user-images.githubusercontent.com/28219016/119899066-ed9a6f00-bf42-11eb-82b3-d45b12c87df8.png)

**Comment by Gibbu** [comment]
Fixed.
