### ISSUE TITLE
Name is being obscured in profile inspection

### ISSUE THREAD

**Issue by RichardLaan** [DiscordStyles/RadialStatus#12]
When you open someone's profile, you cannot see most of the first letter of their name. Examples below.
I propose you can move the text over to the right, move the image to the left, or to disable the RadialStatus on profiles.
In case it's important, my small spacing is 1, large is 1, width is 2.

![temp](https://user-images.githubusercontent.com/85661330/121463400-f8f88c00-c97f-11eb-8fc2-2b2090783df5.png)

As a side note, I made this account for this issue, I will not be monitoring it. If you need any information, contact me. Richard Laan#8197

**Comment by Gibbu** [comment]
Fixed.
