### ISSUE TITLE
Misaligned radial status on profiles

### ISSUE THREAD

**Issue by RichardLaan** [DiscordStyles/RadialStatus#14]
![temp](https://user-images.githubusercontent.com/85661330/121608783-93101100-ca20-11eb-9c5c-c899f9210116.png)

Thank you for your last fix, but it spawned another problem (yay bug squashing!) Anyway, I reverted to as vanilla a discord as possible, and the ring was still off center (its actually an oval.) 

If you need my settings...
small spacing: 1
large spacing: 1
width 2

**Comment by Gibbu** [comment]
Fixed.
