### ISSUE TITLE
Mobile [With or Without Icon] Distorts Profile

### ISSUE THREAD

**Issue by Nahogani** [DiscordStyles/RadialStatus#18]
![image](https://user-images.githubusercontent.com/86008168/122240366-b824d980-ce8f-11eb-8f3a-d43cc0e2b310.png)

![image](https://user-images.githubusercontent.com/86008168/122240689-f7ebc100-ce8f-11eb-8d65-cd9b3671cdc4.png)

As far as I have seen (I have not been able to see anyone using the streaming status) the mobile status is the only one that creates this issue.

**Comment by Gibbu** [comment]
Should be fixed with the newest update.

**Comment by Nahogani** [comment]
![image](https://user-images.githubusercontent.com/86008168/122263067-05ab4180-cea4-11eb-83cf-9c7098f6c87b.png)
![image](https://user-images.githubusercontent.com/86008168/122263091-0b088c00-cea4-11eb-8a76-f64e5f8ae585.png)

Fixed! Thank you very much. <3
