### ISSUE TITLE
[BUG] "Radial Status Theme" don´t work anymore

### ISSUE THREAD

**Issue by BlueStarBRS** [DiscordStyles/RadialStatus#25]
Better Discordtheme "Radial Status Theme" dont work any more.
**i have follow versions** 
Client: **1.0.9002** from Discord 
Theme Version: **2.0** 

can you pls fix that ? 

![image](https://user-images.githubusercontent.com/25110093/127041190-fc581dbb-8e84-4e85-bec8-780a491bec8a.png)
![image](https://user-images.githubusercontent.com/25110093/127041198-2ce8f35e-d254-41f4-b59f-eaec41ef0127.png)

**Comment by JLEE101** [comment]
if you open the theme file in notepad or something and replace
@import url("https://discordstyles.github.io/RadialStatus/base.css");
with
@import url("https://discordstyles.github.io/RadialStatus/dist/RadialStatus.css");
then it works again

**Comment by riridescent** [comment]
This worked. Thank you!

**Comment by BlueStarBRS** [comment]
And the theme get no Update ? There so many users from that

iri ***@***.***> schrieb am Mo., 26. Juli 2021, 23:56:

**Comment by Gibbu** [comment]
Yeah sorry about that. I updated the repo to a new file structure to make developing and contributing to the project a ton easier.

The website doesn't know how to detect if the .theme.css file has been moved. I'm working on that now. Sorry about that :\

**Comment by BlueStarBRS** [comment]
Awesome, thanks!

Ian ***@***.***> schrieb am Di., 27. Juli 2021, 03:49:

**Comment by raffel080108** [comment]
> if you open the theme file in notepad or something and replace
> @import url("https://discordstyles.github.io/RadialStatus/base.css");
> with
> @import url("https://discordstyles.github.io/RadialStatus/dist/RadialStatus.css");
> then it works again

Yup, works, thanks! :D

**Comment by raffel080108** [comment]
> Yeah sorry about that. I updated the repo to a new file structure to make developing and contributing to the project a ton easier.
> 
> The website doesn't know how to detect if the .theme.css file has been moved. I'm working on that now. Sorry about that :\

I mean, can't you just put the new link into the plugin with an update?

**Comment by Gibbu** [comment]
If it worked like that, yes.

**Comment by WafflesDev** [comment]
> > Yeah sorry about that. I updated the repo to a new file structure to make developing and contributing to the project a ton easier.
> > The website doesn't know how to detect if the .theme.css file has been moved. I'm working on that now. Sorry about that :\
> 
> I mean, can't you just put the new link into the plugin with an update?

there are alot of themes that contain this theme within them, so they cant just order an all out change for all of this, unless they make a uniform, non changing link to the file
