### ISSUE TITLE
Theme works, but the backround circle for the stock status still shows.

### ISSUE THREAD

**Issue by TheSlimerX** [DiscordStyles/RadialStatus#27]
![image](https://user-images.githubusercontent.com/48187239/130512756-5ca61d7a-eb61-4c7c-ba4c-c0834a941642.png)

**Comment by Gibbu** [comment]
Seems to be an issue with your other theme.
![24-09 34 - Tuesday - 1629761668](https://user-images.githubusercontent.com/20338746/130532611-7ff38050-1c80-45bd-9445-549a61608463.png)
![24-09 34 - Tuesday - 1629761685](https://user-images.githubusercontent.com/20338746/130532613-2aef674e-fece-4477-ad98-c0e3507c5e91.png)
