### ISSUE TITLE
Radial Status cutting off pfp borders

### ISSUE THREAD

**Issue by KK-Designs** [DiscordStyles/RadialStatus#31]
### Describe the bug
When using Radial Status, it cuts off a small part of the profile picture. See the screenshot below for an example.

### To Reproduce
Install the Radial Status theme

### Screenshots:
Before: 
![image](https://user-images.githubusercontent.com/71038229/141705969-0d0905a2-1729-492b-9627-5729649877ad.png)
After (see edge of glasses and black border surrounding face): 
![image](https://user-images.githubusercontent.com/71038229/141705982-55c37f98-bd23-4f99-acf9-b558c6192039.png)

### Infomation:
**Discord channel:** Stable
**OS:** Windows
**Mod:** BetterDiscord
**Discord language:** English

### Additional context
**Settings:**
```css
  --rs-small-spacing: 2px; /* Gap between avatar and status for members list/dms | MUST end in px */
  --rs-medium-spacing: 3px; /* Gap between avatar and status for User popout | MUST end in px */
  --rs-large-spacing: 4px; /* Gap between avatar and status for User profiles | MUST end in px */

  --rs-small-width:   0.09375em; /* Thickness of status border for members list/dms | MUST end in px */
  --rs-medium-width:  2px; /* Thickness of status border for User popout | MUST end in px */
  --rs-large-width:   3px; /* Thickness of status border for User profile | MUST end in px */

  --rs-avatar-shape: 50%; /* 50% for round - 0% for square */

  --rs-online-color: #43b581; /* Colour for online status */
  --rs-idle-color: #faa61a; /* Colour for idle status */
  --rs-dnd-color: #f04747; /* Colour for dnd status */
  --rs-offline-color: #747f8d; /* Colour for offline status */
  --rs-streaming-color: #643da7; /* Colour for streaming status */  
  --rs-phone-color: var(--rs-online-color); /* Colour of the ring and phone icon when a user is on their phone |  */

  --rs-phone-visible: block; /* Visibility of the phone icon next to a users avatar. | block = visible | none = hidden */
```

**Comment by Gibbu** [comment]
Yep. This is not a bug. Just the only way to achieve to effect. If you wish to remove the spacing, set all the `--rs-[size]-spacing` to `0px`
