### ISSUE TITLE
Avatars blurry

### ISSUE THREAD

**Issue by KK-Designs** [DiscordStyles/RadialStatus#32]
### Describe the bug
When having this theme on, it blurs all of the avatars in the chat and other places. See the screenshot below.

### To Reproduce
Install this theme and click an avatar from the specified places in the "Additional context" area.

### Screenshots
Before: 
![image](https://user-images.githubusercontent.com/71038229/141706410-a797cb76-4cd3-4676-919d-e8926b27b56d.png)

After: 
![image](https://user-images.githubusercontent.com/71038229/141706389-733bf001-31a4-40ed-9ca9-c66500a8bb6d.png)

### Infomation:
**Discord channel:** Stable
**OS:** Windows
**Mod:** BetterDiscord
**Discord language:** English

### Additional context
Happens in the "My Account" area in discord settings, clicking the avatar in chat, and clicking an avatar from the member list.

**Comment by Gibbu** [comment]
I cannot reproduce this.
![image](https://user-images.githubusercontent.com/20338746/141742025-f6867d99-5677-4a8f-bbfa-00562bc349d9.png)
![image](https://user-images.githubusercontent.com/20338746/141742083-1184ac8a-84db-4e9e-bcdc-178388e519dc.png)
![image](https://user-images.githubusercontent.com/20338746/141742131-2b5b73f7-4308-48c7-a208-80bf7816dfd8.png)

**Comment by KK-Designs** [comment]
It fixed itself somehow, working good now 👍
