### ISSUE TITLE
The theme isnt showing.

### ISSUE THREAD

**Issue by gergthewerg** [DiscordStyles/RadialStatus#33]
The theme isnt showing at all in spite of the fact that its loaded and enabled.

**Comment by Gibbu** [comment]
Why didn't you use the Bug Report template? I need information.

**Comment by MaksiWWGaming** [comment]
The theme was working perfectly fine and then I refreshed Discord to clear RAM and it stopped working. Everything is installed how it should be (stopped working like 2h ago).
Discord channel: PTB
OS: Windows 11
Mod: BetterDiscord
Discord language: English

**Comment by Gibbu** [comment]
This should now be fixed.

**Comment by gergthewerg** [comment]
> Why didn't you use the Bug Report template? I need information such as: Discord channel: _((Stable/PTB/Canary))_ OS: _((Windows/Linux/OSX))_ Mod: _((BetterDiscord/Powercord))_ Discord language: _((Your language))_

oh sorry mb! 

The theme isnt showing at all in spite of the fact that its loaded and enabled.
Discord channel: Canary
OS: Windows11
Mod: BetterDiscord
Discord language: English (US)

**Comment by Gibbu** [comment]
Should be fixed. Re-enable your theme.

**Comment by gergthewerg** [comment]
Tysm!! :3
