### ISSUE TITLE
Brief description of the bug

### ISSUE THREAD

**Issue by End3r-z** [DiscordStyles/RadialStatus#34]
The radial status does not show up at all even after redownloading it. It is fully enabled but shows nothing.

Screenshots:
the theme not showing up: https://End3rz.cant-code.lol/​‍​​​‍‍‍​​​​‍​‍​​‍‍​​‍​‍​​‍‍​​
the theme enabled: https://End3rz.cant-code.lol/‍​​‍‍​​​‍​‍‍​‍​‍​‍‍​‍​‍‍​‍​‍​‍

**Information (please complete the following information):**  
Discord channel: *Stable*  
OS: *Windows*  
Mod: *BetterDiscord*  
Discord language: *English*  

Stable 110397 (6016252)
BetterDiscord 1.3.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19042)

**Comment by Gibbu** [comment]
That is because Discord release a massive update, effecting all themes.

**Comment by Gibbu** [comment]
Whoops, did not meant to close the issue.

**Comment by Gibbu** [comment]
Fixed.
