### ISSUE TITLE
[Bug & Enhancement] Own user status 

### ISSUE THREAD

**Issue by koliwbr** [DiscordStyles/RadialStatus#35]
**Describe the bug**  
If i have Radial status enabled, and i speak Radial Status block speak indicator.

My fix: (use at the end of file or paste in CustomCSS)
```
div.wrapper-1VLyxH:not([data-user-id]) > svg > rect{
    visibility: hidden; /* hide the status ring around your own avatar */
}
```

**Screenshots**  
![image](https://user-images.githubusercontent.com/61465776/152941268-45683946-d5f1-4116-9234-bacfffcaf3f1.png)
(No modification)
![image](https://user-images.githubusercontent.com/61465776/152941359-a3daea09-3626-408c-bbee-6149d1af6b85.png)
(like normal)

In VC, speak: (with mod)
![image](https://user-images.githubusercontent.com/61465776/152941519-ac574082-7711-4fe0-aabe-cff4aa58f7f9.png)

in VC, speak, (no mod)
![image](https://user-images.githubusercontent.com/61465776/152941619-182e87cc-9989-4d81-bee4-c9340b4a8893.png)

**Infomation (please complete the following information):**  
Discord channel: *Stable*  
OS: *Linux*  
Mod: *BetterDiscord*  
Discord language: *PL*

**Comment by xFrah** [comment]
No definitive fix for this?

**Comment by koliwbr** [comment]
It's not ideal but try refresh (Ctr+R)

**Comment by xFrah** [comment]
> It's not ideal but try refresh (Ctr+R)

Doesn't do anything since the theme is broken
