### ISSUE TITLE
Voice chat indicator

### ISSUE THREAD

**Issue by VLBRTN** [DiscordStyles/RadialStatus#37]
In voice chat, when i say something, the voice chat indicator circle appears. That looks wierd in RadialStatus for piOS. Maybe, there is the 
same problem in other implementations of RadialStatus.
I have avatar with alpha channel.
![image](https://user-images.githubusercontent.com/67109628/162605398-e1a3c44c-9ea9-46cd-b198-b29c385b380f.png)

**Comment by Gibbu** [comment]
Fixed as of [42da1be](https://github.com/DiscordStyles/RadialStatus/commit/42da1bedf70c64cdc36a45041c1655b192ae37c6).
