### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by ll3macorn** [DiscordStyles/RadialStatus#38]
### Describe the bug
*does not work at all*  

### To Reproduce  
*install*  

### Screenshots
*<img width="119" alt="image" src="https://user-images.githubusercontent.com/69098787/170028389-ddb9425b-79c4-47c3-b7d3-5b400f583ee7.png">*

### Infomation (please complete the following information)
**Discord channel**: *stable*  
**OS**: *OSX*  
**Mod**: *BetterDiscord*  
**Discord language**: *english*  

### Additional context
*just does not work*

**Comment by Gibbu** [comment]
Works just fine.

**Comment by SmolAlli** [comment]
You may want to learn how to use BD addons before going into a repo and making a vague issue.
[Here](https://smolalli.github.io/BetterDiscord/#visual-ptins) is a guide.

**Comment by ll3macorn** [comment]
> You may want to learn how to use BD addons before going into a repo and making a vague issue. [Here](https://smolalli.github.io/BetterDiscord/#visual-ptins) is a guide.

ive been using bd for over 3 years

**Comment by ll3macorn** [comment]
> Works just fine.

well it just started working 24 hours after i made the issue for some reason after not working for like months

**Comment by Gibbu** [comment]
Sounds like a network issue on your end then.

And next time, please provide *any* helpful information.
