### ISSUE TITLE
Radial Status blocks part of the profile picture

### ISSUE THREAD

**Issue by Jahgoda** [DiscordStyles/RadialStatus#39]
### Describe the bug
When clicking to look at a user's profile up close, the radial status blocks the outer rim of their pfp.

### To Reproduce  
Open Discord, check that radial status is applied, click a user's name from the right sidebar.

### Screenshots
Without Radial Status
![Screenshot (903)](https://user-images.githubusercontent.com/106699889/171478089-a5bc43c6-26e9-4c29-a3e1-0189e2bb822e.png)
With Radial Status
![Screenshot (902)](https://user-images.githubusercontent.com/106699889/171478092-06cb334c-13c5-4ef5-8b15-f683029dcf48.png)

### Information (please complete the following information)
**Discord channel**: DM's, Groups, Servers
**OS**: Windows
**Mod**: BetterDiscord
**Discord language**: English

### Additional context
The screenshots show with and without radial status applied.
I'm unsure if this is a bug or not but I'd really like to see it get fixed since it blocks part of the user's pfp.

**Comment by Gibbu** [comment]
As stated in my server
![image](https://user-images.githubusercontent.com/20338746/171628133-6b9be668-6bf9-42bc-953d-4ec8355762ff.png)
