### ISSUE TITLE
Can't Edit Theme Variables

### ISSUE THREAD

**Issue by Maximinvs** [DiscordStyles/RadialStatus#42]
### Describe the bug
There is no longer a theme.css file nor even a dist folder that contains an editable css file to change theme variables.

### To Reproduce  
Try changing the theme variables of any version of RadialStatus. Edit: I backed up an older version and it actually works just fine, regardless the newer versions seem to be missing the theme.css files.

### Infomation (please complete the following information)
Canary
Windows
Powercord
English

**Comment by Gibbu** [comment]
You obviously didn't look. At all.
https://github.com/DiscordStyles/RadialStatus/blob/master/src/core/_root.scss
