### ISSUE TITLE
Pfp has weird cutout when hovered over

### ISSUE THREAD

**Issue by Andrea-moth** [DiscordStyles/RadialStatus#46]
### Describe the bug
When in a users profile hovering over their profile picture there is a cutout left from where the status icon usually is

### To Reproduce  
Hover over a users pfp

### Screenshots
![radial icons error](https://user-images.githubusercontent.com/103472619/191501311-2360034d-9342-48a1-b1f3-85346b7d8d8b.png)

### Infomation 
Stable 148303 (2456cdb)
BetterDiscord 1.6.3
Host 0.0.20 Linux 64-Bit (5.19.9-Arch1-1)

**Comment by Gibbu** [comment]
Fixed
