### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by BlueStarBRS** [DiscordStyles/RadialStatus#47]
### Describe the bug
the new ui updates from discord broke radial status exaple screenshots down below

### Screenshots
![image](https://user-images.githubusercontent.com/25110093/198101948-a37aad1a-5629-4aa8-9d60-0636ffa1c9fe.png)
![image](https://user-images.githubusercontent.com/25110093/198102154-dad87661-e6b3-47c3-80d7-4e2a2ced8e32.png)
![image](https://user-images.githubusercontent.com/25110093/198102254-eb0293ae-7ff2-4507-a6a8-111a3bea42e5.png)

version:
![image](https://user-images.githubusercontent.com/25110093/198102454-cd8aa28f-ae58-4feb-a010-8fd9caf25e30.png)
btw its on cannary on stable the same 

### Additional context
one of the best theme in the wourld <3
i hope i can help you with this report

**Comment by Gibbu** [comment]
Fixed

**Comment by BlueStarBRS** [comment]
@Gibbu love you thx! <3
