### ISSUE TITLE
Mobile Icon

### ISSUE THREAD

**Issue by DracoClaw** [DiscordStyles/RadialStatus#6]
So it's been some time since we discussed this. I did some examples, and I think that putting the Mobile Icon back to were it is in vanilla would look the best.

![image](https://user-images.githubusercontent.com/34274162/116298955-c450bc80-a7a5-11eb-856d-2e9c7635eec0.png)

**Comment by Gibbu** [comment]
The different colour is the only move here. I'm going to add 2 new variables.

`--rs-phone-visible` will be if the user wants to display the phone icon. Options are `block` for visible and `none` for hidden.
`--rs-phone-colour` will be the colour of the ring and the phone icon. This will defaulted to `--rs-online-color`.

**Comment by DracoClaw** [comment]
Any chance you could also add the other option? Just for some customization

**Comment by Gibbu** [comment]
I cannot. The way Discord has structured their avatars and status is really really limiting. I was somewhat able to get it to work but then any time that user typed, updated their status or you clicked on their name it would make the ring go over the phone and removed the substitute background.

**Comment by DracoClaw** [comment]
Couldn't you set a new path that is the ring and phone together? One shape not two.

**Comment by Gibbu** [comment]
No I cannot. As I said before. The way Discord structured their avatars and statuses is very limiting. The only thing I can with work is a `rect` element. I'm more than happy to merge a good way if you can figure one out.
