### ISSUE TITLE
Bug since Discord update

### ISSUE THREAD

**Issue by BySwiizen** [DiscordStyles/RadialStatus#61]
### Describe the bug

_Since the new Discord update, all themes and plugins no longer work. Can you update your theme please?_

### To Reproduce

_Update your Discord and launch it._

### Infomation (please complete the following information)

**Discord channel**: _Stable_  
**OS**: _Windows_  
**Mod**: _BetterDiscord_  
**Discord language**: _FR_

**Comment by Gibbu** [comment]
Thanks to @LewsTherinTelescope RadialStatus is fixed.
