### ISSUE TITLE
Theme doesn't work due to big Discord update

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [DiscordStyles/RadialStatus#64]
### Describe the bug

Due to a big Discord update, this theme is no longer working.

### Infomation (please complete the following information)

**Discord channel**:  _Stable_
**OS**: _Windows_  
**Mod**: _Vencord_  
**Discord language**: _English(?)_

**Comment by BySwiizen** [comment]
I confirm, this broke all themes.

**Comment by Strana** [comment]
Can confirm, my icons are supposed to be square with a square status colour outline, yet they're default.
![image](https://github.com/DiscordStyles/RadialStatus/assets/34879226/41f99161-8e87-4bff-b949-1c30fe5fc55c)

**Comment by Gibbu** [comment]
Fixed.
