### ISSUE TITLE
Circle Invisible after writing something

### ISSUE THREAD

**Issue by dragonfire5020** [DiscordStyles/RadialStatus#8]
Since i updated discord yesterday its not working on some users, it mostly happens if the user writes something and afterwards the circle is invisible (2nd from top)

![Screenshot_1](https://user-images.githubusercontent.com/13822065/117806484-b0539300-b25a-11eb-937e-0daeb21a7976.png)

![Screenshot_2](https://user-images.githubusercontent.com/13822065/117806582-d0835200-b25a-11eb-835a-edced196d3a8.png)

Its not my other theme, I already tried it with the default discord look.

**Comment by Rodanksilos69** [comment]
Same here, but only online circles (pc and mobile) are invisible
Friends list is fine, only convos have this problem

Friends list:
![image](https://user-images.githubusercontent.com/84020045/117812319-565ac980-b26a-11eb-84f9-793d2101e51a.png)

Convos list:
![image](https://user-images.githubusercontent.com/84020045/117812445-75595b80-b26a-11eb-8f5f-3f3f50abc877.png)

**Comment by ModkaVartini** [comment]
![image](https://user-images.githubusercontent.com/81793953/117937446-a184e300-b323-11eb-8e53-4352e76d3921.png)
I integrated RadialStatus into the [comfy](https://github.com/NYRI4/Comfy) theme and I have no problems until someone starts typing.
![image](https://user-images.githubusercontent.com/81793953/117937820-03dde380-b324-11eb-9788-dff22f6b9420.png)
Then, it becomes like this.
it gets fixed when I visit another channel or server and then come back.
is there any fix for this? I really like to use RadialStatus on my themes.

**Comment by Gibbu** [comment]
As I already said. I can't do anything about this.

> Ahh okay. Have to put in the new online status colour. But also Discord for some reason just doesn't render the status indicator.
> As seen in this screenshot:
> ![image](https://user-images.githubusercontent.com/20338746/117824917-36e78f00-b2b2-11eb-8d44-dc18df8120c7.png)

**Comment by Drflash55** [comment]
This seemed to have been fixed for a while... miraculously.

![image](https://user-images.githubusercontent.com/13694448/121447732-436c0f80-c964-11eb-8734-afad3e03e22b.png)
But as of recently, it came back. Not sure if Discord fixed it on their own, or if GIbbu did it.

**Comment by Gibbu** [comment]
They changed it once again.
But just to clarify I cannot fix the users without a status. Example:

The 4th person on this list just don't even render a status. The status indicator doesn't exist inside HTML.
![image](https://user-images.githubusercontent.com/20338746/121520920-d4abb680-ca36-11eb-95b2-c1a1aea5edab.png)
